# Generated by Django 5.2.1 on 2025-06-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
            ],
        ),
    ]
