# Generated by Django 5.2.1 on 2025-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
