# Generated by Django 5.2.1 on 2025-06-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment__id_alter_equipmenttype__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='serial_number_mask',
            field=models.CharField(default='XXXXXXXXXX', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
